const POLYMER_POP = {
  electricViolet: "#6B21E8",
  deepViolet: "#4A0E8F",
  darkerViolet: "#2D0558",
  neonMint: "#00F5A0",
  hotPink: "#FF2D78",
  mangoYellow: "#FFB800",
  brightAzure: "#00BFFF",
  coralRed: "#FF4757",
  deepIndigo: "#1A0533",
  surfaceViolet: "#3D1470",
  surfaceLight: "#5B2AA0",
  cardViolet: "#4C1AA3",
  indentDark: "#2A0A60",
  indentLight: "#7A3FD0",
  textPrimary: "#FFFFFF",
  textSecondary: "rgba(255,255,255,0.7)",
  textMuted: "rgba(255,255,255,0.4)",
  success: "#00F5A0",
  warning: "#FFB800",
  danger: "#FF4757",
  overlayDark: "rgba(26,5,51,0.95)",
};

export default {
  dark: {
    background: POLYMER_POP.deepIndigo,
    surface: POLYMER_POP.surfaceViolet,
    card: POLYMER_POP.cardViolet,
    border: POLYMER_POP.indentDark,
    text: POLYMER_POP.textPrimary,
    textSecondary: POLYMER_POP.textSecondary,
    textMuted: POLYMER_POP.textMuted,
    tint: POLYMER_POP.neonMint,
    accent: POLYMER_POP.hotPink,
    yellow: POLYMER_POP.mangoYellow,
    azure: POLYMER_POP.brightAzure,
    coral: POLYMER_POP.coralRed,
    tabIconDefault: "rgba(255,255,255,0.4)",
    tabIconSelected: POLYMER_POP.neonMint,
    indentShadowDark: POLYMER_POP.indentDark,
    indentShadowLight: POLYMER_POP.indentLight,
    clayHighlight: "rgba(255,255,255,0.25)",
    clayShadow: "rgba(0,0,0,0.5)",
    ...POLYMER_POP,
  },
};

export type ColorTheme = typeof POLYMER_POP;
